### ISSUE TITLE
Opening item sheets does not work

### ISSUE THREAD

**Issue by Orionox** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#201]
While this module is active anytime I attempt to open an item foundryVTT V10 completely freezes. I believe the bug is being caused by an incompatibility with the custom skills/abilities modules. They worked perfectly fine together in v9, only in v10 have they caused a problem together.

**Comment by ghost91-** [comment]
In order to do anything here, I need more details. Please provide the exact version of foundry vtt, AIP, the used game system (including version), and the exact name of the module you think might be conflicting, also including its version. Also, do you see any error message in the console in the dev tools (F12), when the problem appears?

**Comment by ghost91-** [comment]
Closing this due to lack of a response. Please open a new issue when you have more information.
