### ISSUE TITLE
Support for twodsix

### ISSUE THREAD

**Issue by mudgw2** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#214]
Greetings, requesting support for twodsix [https://github.com/xdy/twodsix-foundryvtt](https://github.com/xdy/twodsix-foundryvtt)

**Comment by ghost91-** [comment]
Hey there, I appreciate the interest. Unfortunately, I am not familiar with twodsix at all, so it’s difficult/impossible for me to judge, what autocompletion should be added for exactly (i.e. which fields in which apps, and what data should be used to generate the suggestions). That’s why I won’t do it myself, unless I get specific information about what needs to be done exactly. I am happy to accept PRs, though. Also note that it is possible to add the support on the system side, by using AIP's API. That might make more sense since people there obviously have more knowledge an out the system.

**Comment by Twinkee** [comment]
Talked to the guy working on twodsix. They've recently added active effects and are pushing an update with Autocomplete compatibility later.

**Comment by marvin9257** [comment]
Hi,
I'm one of the maintainers for Twodsix.  I've added support on the system side for active effects.  I might add support for other fields at some point. Cheers.

**Comment by ghost91-** [comment]
Nice, closing this then :)
