### ISSUE TITLE
How can I support text fields added in render hooks?

### ISSUE THREAD

**Issue by dmrickey** [ghost-fvtt/FVTT-Autocomplete-Inline-Properties#412]
Is there any way to support text fields that are added via render hooks?

**Comment by ghost91-** [comment]
Good question, it probably depends on the order in which the hooks are executed. If the hook adding the field runs before AIP's hook, it should probably work, but otherwise, I don’t really see an option. Unfortunately, it’s not easy to control the order of hooks, it depends on the order in which they are registered. AIP registers its application hooks during the setup hook, so if the field adding hook is registered before that (e.g., during the init hook), it should work. If it does not, I’d need to investigate why, when I’m back from vacation (will be back on Monday, 11.09.).

**Comment by dmrickey** [comment]
My hooks are registered during startup of my mod (not in a hook, just in the entry file). Which I think is technically before the init hook? I'm not sure. The system is already supported (pf1) and in my mod I'm registered for the `renderItemSheet` hook and adding in more fields.

**Comment by ghost91-** [comment]
Yes, that’s before the init hook, so it should be fine. Then it should be just a matter of making sure that your custom input fields are getting picked up by the configuration for AIP.

You can see the config for the pf1 item sheet here: https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/blob/main/src/package-config.js#L230. Most likely, your inputs don’t match those selectors. You can either change your inputs so that they match, or change the configuration to add additional selectors.

To do the latter, you can register for the aipSetup hook, which passes this whole configuration object as parameter to the callback. There, you can modify it inplace, to add the selectors for your inputs. See https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/blob/main/CONTRIBUTING.md#adding-a-package-config for more details about the hook.

**Comment by dmrickey** [comment]
Hm, I looked at that and thought they should match.. I'll take a closer look

**Comment by dmrickey** [comment]
![image](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/assets/3664822/60f40111-503d-493e-930a-2a52a19cbee6)
![image](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/assets/3664822/85564b50-d0db-4749-a852-0c90cdf44ce7)

This is the config
![image](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/assets/3664822/66cc88af-cb2b-40ea-98f4-467984b1624d)

AIP is showing up for other fields, but not for the fields I'm adding in my hook

**Comment by dmrickey** [comment]
Ok interesting. I did a bit of digging. You're mod is registering for `renderItemSheetPF` whereas I'm registering for the slightly more generic `renderItemSheet`.

![image](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/assets/3664822/1f435431-7977-4773-a39f-5f673a153c90)

Turning on hook debugging it looks like yours is emitted first.

![image](https://github.com/ghost-fvtt/FVTT-Autocomplete-Inline-Properties/assets/3664822/dfdb7b55-a488-4f51-b26f-0eb845b9cf24)

I wouldn't say either one was wrong. It looks like I can just update mine to use `renderItemSheetPF` and then it looks like it will work. But it might be worthwhile to update AIP to use the slightly more generic `renderItemSheet` because someone else may do something similar in the future and there probably shouldn't be any difference between them as far as AIP is concerned

**Comment by ghost91-** [comment]
Since the configuration is system specific, I think it makes sense to use the system specific render hook. I really only want to register for the the ItemSheetPf being rendered, in this case, not any other item sheet. I’ll keep it like that.
